//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PassPro.Entities
{
    /// <summary>
    /// 实体类loginlog。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("loginlogs")]
    [Serializable]
    public partial class loginlog : Entity
    {
        #region Model
		private string _id;
		private string _userid;
		private string _ip;
		private DateTime _logintime;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public string id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("userid")]
		public string userid
		{
			get{ return _userid; }
			set
			{
				this.OnPropertyValueChange("userid");
				this._userid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ip")]
		public string ip
		{
			get{ return _ip; }
			set
			{
				this.OnPropertyValueChange("ip");
				this._ip = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("logintime")]
		public DateTime logintime
		{
			get{ return _logintime; }
			set
			{
				this.OnPropertyValueChange("logintime");
				this._logintime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.userid,
				_.ip,
				_.logintime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._userid,
				this._ip,
				this._logintime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "loginlogs");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "loginlogs", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field userid = new Field("userid", "loginlogs", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ip = new Field("ip", "loginlogs", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field logintime = new Field("logintime", "loginlogs", "");
        }
        #endregion
	}
}