//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PassPro.Entities
{
    /// <summary>
    /// 实体类user。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("users")]
    [Serializable]
    public partial class user : Entity
    {
        #region Model
		private string _id;
		private string _password;
		private string _email;
		private string _phone;
		private string _license;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public string id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("password")]
		public string password
		{
			get{ return _password; }
			set
			{
				this.OnPropertyValueChange("password");
				this._password = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("email")]
		public string email
		{
			get{ return _email; }
			set
			{
				this.OnPropertyValueChange("email");
				this._email = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("phone")]
		public string phone
		{
			get{ return _phone; }
			set
			{
				this.OnPropertyValueChange("phone");
				this._phone = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("license")]
		public string license
		{
			get{ return _license; }
			set
			{
				this.OnPropertyValueChange("license");
				this._license = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.password,
				_.email,
				_.phone,
				_.license,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._password,
				this._email,
				this._phone,
				this._license,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "users");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field password = new Field("password", "users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field email = new Field("email", "users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field phone = new Field("phone", "users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field license = new Field("license", "users", "");
        }
        #endregion
	}

    public partial class user
    {
        /// <summary>
        /// 验证码
        /// </summary>
        public string ValidateCode { get; set; }
    }
}